version: '3'
services:

  #Php-fpm Service
  php-fpm:
    build:
      context: docker/php-fpm/
      dockerfile: Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=PHPSTORM"
    working_dir: /var/www
    volumes:
      - ./www:/var/www
      - ./docker/php-fpm/local.ini:/usr/local/etc/php-fpm/conf.d/local.ini
    links:
      - mariadb
    networks:
      - laravel-network

  #Nginx Service
  nginx:
    build:
      context: ./docker/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - 80:8080
      - 443:4430
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./hosts/:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./www:/var/www
    links:
      - php-fpm
      - mariadb
    networks:
      - laravel-network

  #MariaDB Service
  mariadb:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network

  #PHPMyadmin Service
  pma:
    image: phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    tty: true
    ports:
      - 81:80
    environment:
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    links:
      - nginx
      - mariadb
    networks:
      - laravel-network


#Docker Networks
networks:
  laravel-network:
    driver: bridge
#Volumes
#volumes:
#  dbdata:
#    driver: local